Make API tested library static since it is needed for only testing (#594)
This solves following issue 
```
│ │ [bin/gtests/libcuopt/C_API_TEST] links against:
 │ │  ├─ lib/libcuopt.so (libcuopt)
 │ │  ├─ lib/libgmock_main.so.1.17.0 (gtest)
 │ │  ├─ lib/libgcc_s.so.1 (libgcc)
 │ │  ├─ lib/libstdc++.so.6.0.34 (libstdcxx)
 │ │  ├─ libc.so.6 (system)
 │ │  └─ libc_api_tester.so
 │ │
 │ ╰─────────────────── (took 3 seconds)
 │
 ╰─────────────────── (took 61 seconds)
Error:   × linking check error: Overlinking against: libc_api_tester.so (file: "bin/
  │ gtests/libcuopt/C_API_TEST")
  ╰─▶ Overlinking against: libc_api_tester.so (file: "bin/gtests/libcuopt/
      C_API_TEST")
```

Authors:
  - Ramakrishnap (https://github.com/rgsl888prabhu)

Approvers:
  - Rajesh Gandham (https://github.com/rg20)
  - Trevor McKay (https://github.com/tmckayus)

URL: https://github.com/NVIDIA/cuopt/pull/594