CUDA 13 support: follow-ups (#377)
Contributes to https://github.com/rapidsai/build-planning/issues/208

* updates all GitHub Actions branch references back to `branch-25.10`, now that https://github.com/rapidsai/shared-workflows/pull/413 is merged
* fixes docs mistakes (https://github.com/NVIDIA/cuopt/pull/366#discussion_r2325719184)
* fixes nightly builds

Nightly wheel builds of `cuopt-mps-parser` are failing like this:

> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

([wheel-build-cuopt-mps-parser link](https://github.com/NVIDIA/cuopt/actions/runs/17501959410/job/49716771454))

Because I forgot to bring over all of the artifact-naming changes made in `pr.yaml` to the corresponding entries on `build.yaml`, sorry 😬

Authors:
  - James Lamb (https://github.com/jameslamb)
  - Ramakrishnap (https://github.com/rgsl888prabhu)

Approvers:
  - Ramakrishnap (https://github.com/rgsl888prabhu)

URL: https://github.com/NVIDIA/cuopt/pull/377